CREATE TABLE crashes (
	`CRASH DATE` varchar(255),
    `CRASH TIME` varchar(255),
    BOROUGH varchar(255),
    `ZIP CODE` varchar(255),
    `NUMBER OF PERSONS INJURED` varchar(255),
    `NUMBER OF PERSONS KILLED` varchar(255),
    `NUMBER OF PEDESTRIANS INJURED` int,
    `NUMBER OF PEDESTRIANS KILLED` int,
    `NUMBER OF CYCLIST INJURED` int,
    `NUMBER OF CYCLIST KILLED` int,
    `NUMBER OF MOTORIST INJURED`int,
    `NUMBER OF MOTORIST KILLED`int,
    `CONTRIBUTING FACTOR VEHICLE 1` varchar(1000),
    `CONTRIBUTING FACTOR VEHICLE 2` varchar(1000),
    `CONTRIBUTING FACTOR VEHICLE 3` varchar(1000),
    `CONTRIBUTING FACTOR VEHICLE 4` varchar(1000),
    `CONTRIBUTING FACTOR VEHICLE 5` varchar(1000),
    COLLISION_ID int,
    `VEHICLE TYPE CODE 1` varchar(255),
    `VEHICLE TYPE CODE 2` varchar(255),
    `VEHICLE TYPE CODE 3` varchar(255),
    `VEHICLE TYPE CODE 4` varchar(255),
    `VEHICLE TYPE CODE 5` varchar(255),
    PRIMARY KEY(COLLISION_ID)
    );
    
CREATE TABLE persons (
	UNIQUE_ID int,
    COLLISION_ID int,
    CRASH_DATE varchar(255),
    CRASH_TIME varchar(255),
    PERSON_ID varchar(255),
    PERSON_TYPE varchar(255),
    PERSON_INJURY varchar(255),
    VEHICLE_ID int,
    PERSON_AGE int,
    BODILY_INJURY varchar(255),
    POSITION_IN_VEHICLE varchar(255),
    SAFETY_EQUIPMENT varchar(255),
    PED_LOCATION varchar(255),
    PED_ACTION varchar(255),
    PED_ROLE varchar(255),
    PERSON_SEX varchar(255),
    PRIMARY KEY(UNIQUE_ID)
    );
    
CREATE TABLE vehicles (
	UNIQUE_ID int,
    COLLISION_ID int,
    CRASH_DATE varchar(255),
    CRASH_TIME varchar(255),
    VEHICLE_ID varchar(1000),
    VEHICLE_TYPE varchar(255),
    VEHICLE_MAKE varchar(255),
    VEHICLE_MODEL varchar(255),
    VEHICLE_YEAR varchar(255),
    VEHICLE_OCCUPANTS varchar(255),
    DRIVER_SEX varchar(255),
    PRE_CRASH text,
    CONTRIBUTING_FACTOR_1 text,
    CONTRIBUTING_FACTOR_2 text,
    PRIMARY KEY(UNIQUE_ID)
    );